quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=gabrielbuzzi
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/clinica

quarkus.hibernate-orm.database.generation=update