quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=gabrielbuzzi
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/academia

# atualiza a tabela automaticamente
quarkus.hibernate-orm.database.generation=update

# show queries SQL no terminal
quarkus.hibernate-orm.log.sql=true